spring.application.name=adp

#spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
#spring.jpa.database-platform.dialect=org.hibernate.community.dialect.DerbyDialect
#spring.datasource.url=jdbc:derby://localhost:1527/adp_derby
#spring.datasource.initialization-mode=never
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.cunwskzfigjpxboyxsxo&password=XhVPmRLYBTAyx6j3
spring.jpa.generate-ddl=true